# Generated by Django 4.1.3 on 2022-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='poll_app.ipmodel'),
        ),
    ]
