# Generated by Django 4.1.7 on 2023-03-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_ipmodel_question_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
