# Generated by Django 5.1.5 on 2025-02-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_remove_choice_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
